# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.IntegerField(default=0),
        ),
    ]
